bp<-read.csv("/home/sean/Desktop/brainPaste.csv")
means<-aggregate(bp$gray.value,by=list(bp$thickness),FUN=mean)
names(means)<-c("thickness","average.gray.value")
plot(gray.value~thickness,data=bp,col="#43A2CA76",pch=16,xlab="Brain Paste thickness",ylab="gray level")
points(means$thickness,means$average.gray.value,pch=15,col="#43A2CA")
lm1<-lm(average.gray.value~thickness,data=means)
summary(lm1)
abline(lm1,lwd=3,col="gray50")
CI<-predict(lm1,newdata=data.frame(thickness=seq(from=10,to=60,by=.1)),interval="confidence")
CI<-as.data.frame(CI)
CI$newdata<-seq(from=10,to=60,by=.1)
lines(CI$newdata,CI$lwr,lwd=2,lty=3)
lines(CI$newdata,CI$upr,lwd=2,lty=3)
